In [382]:
#!pip install yfinance
#!pip install pandas-ta

In [383]:
import requests
import bs4 as bs
import pickle

import datetime as dt
import os

import pandas as pd
import pandas_datareader.data as pdr
import pandas_ta as ta

import numpy as np

import math

import yfinance as yf

In [384]:
import sklearn

from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler, MinMaxScaler, RobustScaler, KBinsDiscretizer
#import category_encoders as ce
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# GET THE TRADING DATA

In [385]:
#SPX500 data

df_analisys = yf.download('^GSPC',period="30d", interval="15m")
#df_analisys = yf.download('^GSPC', interval="5m", start="2022-02-16", end="2022-03-03")

df_analisys = df_analisys.reset_index()

print(df_analisys.shape)
df_analisys

[*********************100%***********************]  1 of 1 completed
(765, 7)

,Datetime,Open,High,Low,Close,Adj Close,Volume
0,2022-01-25 09:30:00-05:00,4366.640137,4366.640137,4334.669922,4337.319824,4337.319824,108392971
1,2022-01-25 09:45:00-05:00,4337.229980,4337.229980,4299.529785,4304.509766,4304.509766,138840281
2,2022-01-25 10:00:00-05:00,4305.919922,4312.720215,4287.109863,4310.790039,4310.790039,118896967
3,2022-01-25 10:15:00-05:00,4311.529785,4337.419922,4305.700195,4337.419922,4337.419922,107561501
4,2022-01-25 10:30:00-05:00,4338.089844,4341.939941,4319.390137,4341.850098,4341.850098,103533391
...,...,...,...,...,...,...,...
760,2022-03-08 11:00:00-05:00,4197.919922,4201.850098,4182.160156,4187.669922,4187.669922,113042629
761,2022-03-08 11:15:00-05:00,4187.790039,4189.729980,4169.660156,4172.609863,4172.609863,100206000
762,2022-03-08 11:30:00-05:00,4172.520020,4172.799805,4157.870117,4164.600098,4164.600098,100670000
763,2022-03-08 11:45:00-05:00,4164.779785,4191.149902,4164.680176,4183.770020,4183.770020,86722000
764,2022-03-08 12:00:41-05:00,4184.129883,4184.129883,4184.129883,4184.129883,4184.129883,0

In [386]:
df_analisys.columns

Index(['Datetime', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [387]:
# SAVING POINT

DIR_OUTPUTS = r'C:\Users\willi\Documents\EJERCICIOS\TRADING\outputs/'

df_analisys.to_pickle(DIR_OUTPUTS + 'df_spx500_15m_raw' + '.pkl')
print(df_analisys.shape)

(765, 7)

In [388]:
#df_analisys[ (df_analisys['Datetime']>=dt.datetime(2022,3,3,15,30))]

# Candles computations

In [389]:
#Fixes the trading date
df_analisys['Datetime'] = df_analisys['Datetime'].dt.tz_localize(None)
df_analisys['Datetime']

0     2022-01-25 09:30:00
1     2022-01-25 09:45:00
2     2022-01-25 10:00:00
3     2022-01-25 10:15:00
4     2022-01-25 10:30:00
              ...
760   2022-03-08 11:00:00
761   2022-03-08 11:15:00
762   2022-03-08 11:30:00
763   2022-03-08 11:45:00
764   2022-03-08 12:00:41
Name: Datetime, Length: 765, dtype: datetime64[ns]

In [390]:
df_analisys['date'] = df_analisys['Datetime'].apply(lambda x: x.date())
df_analisys['date']

0      2022-01-25
1      2022-01-25
2      2022-01-25
3      2022-01-25
4      2022-01-25
          ...
760    2022-03-08
761    2022-03-08
762    2022-03-08
763    2022-03-08
764    2022-03-08
Name: date, Length: 765, dtype: object

In [391]:
#Computes body sizes

df_analisys['body_size'] = df_analisys['Close'] - df_analisys['Open']
df_analisys['abs_body_size'] = abs(df_analisys['body_size'])
df_analisys['upper_tail_size'] = df_analisys['High'] - df_analisys[['Open','Close']].max(axis=1)
df_analisys['lower_tail_size'] = df_analisys[['Open','Close']].min(axis=1) - df_analisys['Low']

df_analisys[0:50]

,Datetime,Open,High,Low,Close,Adj Close,Volume,date,body_size,abs_body_size,upper_tail_size,lower_tail_size
0,2022-01-25 09:30:00,4366.640137,4366.640137,4334.669922,4337.319824,4337.319824,108392971,2022-01-25,-29.320312,29.320312,0.000000,2.649902
1,2022-01-25 09:45:00,4337.229980,4337.229980,4299.529785,4304.509766,4304.509766,138840281,2022-01-25,-32.720215,32.720215,0.000000,4.979980
2,2022-01-25 10:00:00,4305.919922,4312.720215,4287.109863,4310.790039,4310.790039,118896967,2022-01-25,4.870117,4.870117,1.930176,18.810059
3,2022-01-25 10:15:00,4311.529785,4337.419922,4305.700195,4337.419922,4337.419922,107561501,2022-01-25,25.890137,25.890137,0.000000,5.829590
4,2022-01-25 10:30:00,4338.089844,4341.939941,4319.390137,4341.850098,4341.850098,103533391,2022-01-25,3.760254,3.760254,0.089844,18.699707
5,2022-01-25 10:45:00,4343.240234,4353.120117,4323.660156,4325.319824,4325.319824,99688508,2022-01-25,-17.920410,17.920410,9.879883,1.659668
6,2022-01-25 11:00:00,4325.419922,4334.859863,4314.680176,4316.259766,4316.259766,84075384,2022-01-25,-9.160156,9.160156,9.439941,1.579590
7,2022-01-25 11:15:00,4316.290039,4342.810059,4313.609863,4335.720215,4335.720215,86186449,2022-01-25,19.430176,19.430176,7.089844,2.680176
8,2022-01-25 11:30:00,4335.709961,4336.669922,4307.060059,4316.549805,4316.549805,80641214,2022-01-25,-19.160156,19.160156,0.959961,9.489746
9,2022-01-25 11:45:00,4316.419922,4331.439941,4311.990234,4312.290039,4312.290039,75043000,2022-01-25,-4.129883,4.129883,15.020020,0.299805
10,2022-01-25 12:00:00,4312.270020,4334.240234,4309.939941,4331.560059,4331.560059,70800000,2022-01-25,19.290039,19.290039,2.680176,2.330078
11,2022-01-25 12:15:00,4331.430176,4341.770020,4318.879883,4337.600098,4337.600098,76399000,2022-01-25,6.169922,6.169922,4.169922,12.550293
12,2022-01-25 12:30:00,4337.680176,4337.680176,4320.049805,4329.770020,4329.770020,66247000,2022-01-25,-7.910156,7.910156,0.000000,9.720215
13,2022-01-25 12:45:00,4329.740234,4332.270020,4315.310059,4328.459961,4328.459961,63573000,2022-01-25,-1.280273,1.280273,2.529785,13.149902
14,2022-01-25 13:00:00,4328.410156,4331.339844,4317.259766,4329.770020,4329.770020,65380000,2022-01-25,1.359863,1.359863,1.569824,11.150391
15,2022-01-25 13:15:00,4329.759766,4349.810059,4327.520020,4349.290039,4349.290039,65788000,2022-01-25,19.530273,19.530273,0.520020,2.239746
16,2022-01-25 13:30:00,4349.209961,4359.189941,4346.180176,4357.470215,4357.470215,73583000,2022-01-25,8.260254,8.260254,1.719727,3.029785
17,2022-01-25 13:45:00,4357.390137,4377.479980,4354.709961,4377.479980,4377.479980,80984000,2022-01-25,20.089844,20.089844,0.000000,2.680176
18,2022-01-25 14:00:00,4377.470215,4384.069824,4364.490234,4382.450195,4382.450195,80242000,2022-01-25,4.979980,4.979980,1.619629,12.979980
19,2022-01-25 14:15:00,4382.410156,4391.839844,4381.339844,4387.890137,4387.890137,86695000,2022-01-25,5.479980,5.479980,3.949707,1.070312
20,2022-01-25 14:30:00,4387.870117,4397.959961,4376.959961,4397.629883,4397.629883,83905000,2022-01-25,9.759766,9.759766,0.330078,10.910156
21,2022-01-25 14:45:00,4397.569824,4411.009766,4396.000000,4409.709961,4409.709961,92814000,2022-01-25,12.140137,12.140137,1.299805,1.569824
22,2022-01-25 15:00:00,4409.709961,4410.220215,4383.660156,4385.339844,4385.339844,98568000,2022-01-25,-24.370117,24.370117,0.510254,1.679688
23,2022-01-25 15:15:00,4385.319824,4398.049805,4365.970215,4367.189941,4367.189941,99214000,2022-01-25,-18.129883,18.129883,12.729980,1.219727
24,2022-01-25 15:30:00,4368.250000,4381.549805,4357.729980,4371.689941,4371.689941,128570000,2022-01-25,3.439941,3.439941,9.859863,10.520020
25,2022-01-25 15:45:00,4371.709961,4379.120117,4349.220215,4358.029785,4358.029785,321538000,2022-01-25,-13.680176,13.680176,7.410156,8.809570
26,2022-01-26 09:30:00,4408.430176,4424.770020,4403.020020,4406.649902,4406.649902,93410340,2022-01-26,-1.780273,1.780273,16.339844,3.629883
27,2022-01-26 09:45:00,4406.830078,4436.930176,4406.830078,4432.410156,4432.410156,123034861,2022-01-26,25.580078,25.580078,4.520020,0.000000
28,2022-01-26 10:00:00,4433.220215,4444.830078,4424.520020,4425.799805,4425.799805,107898177,2022-01-26,-7.420410,7.420410,11.609863,1.279785
29,2022-01-26 10:15:00,4425.580078,4429.939941,4400.970215,4405.220215,4405.220215,107347769,2022-01-26,-20.359863,20.359863,4.359863,4.250000
30,2022-01-26 10:30:00,4405.250000,4407.950195,4392.250000,4393.600098,4393.600098,96400671,2022-01-26,-11.649902,11.649902,2.700195,1.350098
31,2022-01-26 10:45:00,4393.709961,4407.029785,4390.109863,4405.299805,4405.299805,86379656,2022-01-26,11.589844,11.589844,1.729980,3.600098
32,2022-01-26 11:00:00,4405.209961,4419.359863,4398.000000,4418.250000,4418.250000,87060162,2022-01-26,13.040039,13.040039,1.109863,7.209961
33,2022-01-26 11:15:00,4418.299805,4424.009766,4414.259766,4420.470215,4420.470215,73316953,2022-01-26,2.170410,2.170410,3.539551,4.040039
34,2022-01-26 11:30:00,4420.390137,4427.439941,4416.370117,4425.479980,4425.479980,70667524,2022-01-26,5.089844,5.089844,1.959961,4.020020
35,2022-01-26 11:45:00,4425.390137,4427.640137,4412.259766,4421.040039,4421.040039,62616023,2022-01-26,-4.350098,4.350098,2.250000,8.780273
36,2022-01-26 12:00:00,4421.040039,4429.919922,4420.399902,4428.000000,4428.000000,63163000,2022-01-26,6.959961,6.959961,1.919922,0.640137
37,2022-01-26 12:15:00,4428.189941,4429.899902,4423.959961,4428.470215,4428.470215,57191000,2022-01-26,0.280273,0.280273,1.429688,4.229980
38,2022-01-26 12:30:00,4428.560059,4435.370117,4424.649902,4435.020020,4435.020020,65312000,2022-01-26,6.459961,6.459961,0.350098,3.910156
39,2022-01-26 12:45:00,4435.040039,4435.169922,4430.160156,4433.850098,4433.850098,65884000,2022-01-26,-1.189941,1.189941,0.129883,3.689941
40,2022-01-26 13:00:00,4433.930176,4434.209961,4417.759766,4427.709961,4427.709961,66169000,2022-01-26,-6.220215,6.220215,0.279785,9.950195
41,2022-01-26 13:15:00,4427.549805,4427.839844,4415.750000,4422.330078,4422.330078,57383000,2022-01-26,-5.219727,5.219727,0.290039,6.580078
42,2022-01-26 13:30:00,4422.299805,4425.299805,4418.709961,4422.540039,4422.540039,59435000,2022-01-26,0.240234,0.240234,2.759766,3.589844
43,2022-01-26 13:45:00,4422.529785,4427.490234,4419.029785,4422.000000,4422.000000,58950000,2022-01-26,-0.529785,0.529785,4.960449,2.970215
44,2022-01-26 14:00:00,4422.040039,4453.229980,4403.939941,4407.729980,4407.729980,132913000,2022-01-26,-14.310059,14.310059,31.189941,3.790039
45,2022-01-26 14:15:00,4407.520020,4432.899902,4404.339844,4429.819824,4429.819824,99883000,2022-01-26,22.299805,22.299805,3.080078,3.180176
46,2022-01-26 14:30:00,4429.569824,4433.529785,4393.339844,4393.339844,4393.339844,137426000,2022-01-26,-36.229980,36.229980,3.959961,0.000000
47,2022-01-26 14:45:00,4391.770020,4391.770020,4359.350098,4377.399902,4377.399902,158011000,2022-01-26,-14.370117,14.370117,0.000000,18.049805
48,2022-01-26 15:00:00,4377.259766,4377.259766,4316.939941,4328.060059,4328.060059,157222000,2022-01-26,-49.199707,49.199707,0.000000,11.120117
49,2022-01-26 15:15:00,4328.180176,4344.100098,4304.799805,4344.000000,4344.000000,145541000,2022-01-26,15.819824,15.819824,0.100098,23.380371

In [392]:
#Computes candles color
df_analisys['body_disposal']=None
df_analisys.loc[df_analisys['body_size']>0,'body_disposal'] = 1
df_analisys.loc[df_analisys['body_size']<0,'body_disposal'] = 0

print(df_analisys['body_disposal'].value_counts(dropna=False).reset_index().sort_values(['index'],ascending = True))

   index  body_disposal
1    0.0            380
0    1.0            384
2    NaN              1

# Target signal

In [ ]:
#Computes Target signal

nro_rows = len(df_analisys)
for i in range(0,nro_rows):
    
    profit_threshold = 20
    
    try:
        #Searches for the after indexes where the profit threshold is fullfilled 
        s_threshold = ((df_analisys['Close'][i] - df_analisys['Close'].iloc[i+1:]).abs() > profit_threshold)
        idxs = s_threshold[s_threshold].index
        
        try:
            target_idx = [min(idxs)]
        except:
            target_idx = []
        
        df_data = df_analisys.iloc[target_idx]

        Datetime = df_analisys['Datetime'][i]

        keepcols = ['Datetime','Close']
        df_data = df_data[keepcols]

        dic_rencols = {
            'Datetime':'target_date',
            'Close': 'target_close',
        }

        df_data = df_data.rename(columns=dic_rencols)
        df_data['Datetime'] = Datetime

        if i == 0:
            df_target =df_data.copy()
        else:
            df_target =df_target.append(df_data).copy()
            
    except:
        pass
        
df_target = df_target.reset_index(drop=True)
df_target

In [ ]:
df_analisys_01 = pd.merge(df_analisys,
                         df_target,
                         on = ['Datetime'],
                         how = 'left').copy()

#Computes the target difference in closure prices
df_analisys_01['target_difference'] =  round( df_analisys_01['target_close'] - df_analisys_01['Close'] )

print(df_analisys.shape)
print(df_analisys_01.shape)

print(df_analisys_01['target_difference'].value_counts(dropna=False).reset_index().sort_values(['index'],ascending = True))

df_analisys_01

In [ ]:
df_varbins = df_analisys_01[['target_difference']]
df_varbins['target_bins'] = pd.qcut(df_varbins['target_difference'], 20, duplicates='drop')
df_varbins['target_bins'] = df_varbins['target_bins'].cat.codes.apply(lambda x: "{:02d}".format(x+1)) + '-' + df_varbins['target_bins'].astype(str)

print(df_varbins['target_bins'].value_counts(dropna=False).reset_index().sort_values(['index']))

In [ ]:
#Computes the target difference in transcurred time
df_analisys_01['target_date_diff'] =  df_analisys_01['target_date'] - df_analisys_01['Datetime']
df_analisys_01['target_date_diff'] = df_analisys_01['target_date_diff'] / np.timedelta64(1,'m')

df_analisys_01

In [ ]:
df_varbins = df_analisys_01[['target_date_diff']]
df_varbins['target_date_bins'] = pd.qcut(df_varbins['target_date_diff'], 20, duplicates='drop')
df_varbins['target_date_bins'] = df_varbins['target_date_bins'].cat.codes.apply(lambda x: "{:02d}".format(x+1)) + '-' + df_varbins['target_date_bins'].astype(str)

print(df_varbins['target_date_bins'].value_counts(dropna=False).reset_index().sort_values(['index']))

In [ ]:
# Computes high time to produce additional categories fo the target

df_varbins = df_varbins.sort_values(['target_date_diff'])
df_varbins = df_varbins[df_varbins.notna().all(axis=1)]
size = round(len(df_varbins)*(0.5))

high_time = df_varbins.iloc[size,:]['target_date_diff']
high_time

In [ ]:
mean_time = df_varbins['target_date_diff'].mode()
print('Mean awaiting time to profit: ', mean_time)

In [ ]:
#computes the target order movement
df_analisys_01['target_order'] = 'NULL'

df_analisys_01.loc[df_analisys_01['target_difference'] < 0, 'target_order'] = 'SELL'

df_analisys_01.loc[(df_analisys_01['target_difference'] < 0)
                   &(df_analisys_01['target_date_diff'] > high_time), 'target_order'] = 'SELL2'


df_analisys_01.loc[df_analisys_01['target_difference'] > 0, 'target_order'] = 'BUY'

df_analisys_01.loc[(df_analisys_01['target_difference'] > 0)
                   &(df_analisys_01['target_date_diff'] > high_time), 'target_order'] = 'BUY2'


df_analisys_01.loc[abs(df_analisys_01['target_difference']) < profit_threshold, 'target_order'] = 'NULL'

df_analisys_01['target_order_bin'] = 0
df_analisys_01.loc[df_analisys_01['target_order'] == 'BUY', 'target_order_bin'] = 1

print(df_analisys_01['target_order'].value_counts(dropna=False).reset_index().sort_values(['index'],ascending = True))
print(df_analisys_01['target_order_bin'].value_counts(dropna=False).reset_index().sort_values(['index'],ascending = True))

# MACD and EMA indicators

In [ ]:
# # Calculate MACD values using the pandas_ta library
df_macd = df_analisys_01.ta.macd(close='Close', fast=12, slow=26, signal=9, append=True)
df_macd

In [ ]:
ewm50 = df_analisys_01['Close'].ewm(span=50, adjust=False, min_periods=50).mean()
ewm200 = df_analisys_01['Close'].ewm(span=200, adjust=False, min_periods=200).mean()

df_macd['ewm50'] = ewm50
df_macd['ewm200'] = ewm200

#df_analisys_01['ewm50'] = ewm50
#df_analisys_01['ewm200'] = ewm200

df_analisys_01['diff_ewm50'] = df_analisys_01['Close'] - ewm50
df_analisys_01['diff_ewm200'] = df_analisys_01['Close'] - ewm200

df_analisys_01

In [ ]:
#Keeps only the data where MACD is available

df_analisys_02 = df_analisys_01[df_macd.notna().all(axis=1)]

#df_macd[df_macd.notna().all(axis=1)]

print(df_analisys_01.shape)
print(df_analisys_02.shape)

df_analisys_02

In [ ]:
df_varbins = df_analisys_02[['diff_ewm50']]
df_varbins['diff_bins'] = pd.qcut(df_varbins['diff_ewm50'], 20, duplicates='drop')
df_varbins['diff_bins'] = df_varbins['diff_bins'].cat.codes.apply(lambda x: "{:02d}".format(x+1)) + '-' + df_varbins['diff_bins'].astype(str)



print(df_varbins['diff_bins'].value_counts(dropna=False).reset_index().sort_values(['index']))

df_varbins = abs(df_analisys_02[['diff_ewm50']])
print('Absolute mean difference with: ' ,df_varbins.mean())

df_varbins = abs(df_analisys_02[['diff_ewm200']])
print('Absolute mean difference with: ' ,df_varbins.mean())

# Data preparation

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

## Close price info

In [ ]:
# Prepares previos close info as input variables

for i in range(0,len(df_analisys_02)):
    #i=2
    
    ###############################################################################################
    nro_close_lag = 100

    if i==0:
        X = df_analisys_02.iloc[-(nro_close_lag + i):,][['Close']]
        Datetime = df_analisys_02.iloc[-1:,]['Datetime'].iloc[0]
    else:
        X = df_analisys_02.iloc[-(nro_close_lag + i):-i,][['Close']]
        Datetime = df_analisys_02.iloc[-(i+1):,]['Datetime'].iloc[0]

    # define standard scaler
    sscaler = StandardScaler()

    # transform data
    X_ss1 = sscaler.fit_transform(X)
    #print(X2)

    # Obtains the df of variables of close lags
    ls_columns = ['ss1_close_' + str(x) for x in range(len(X_ss1),0,-1) ]
    df_ssdata1 = pd.DataFrame(X_ss1.T,columns=ls_columns)
    ###############################################################################################
    
    ###############################################################################################
    #Computes slopes before the last close
    ls_linreg_coefs = []
    
    for j in [3,5,8,13]:
        y = X_ss1[-j:]
        x = np.array([range(0,j)]).reshape(-1,1)


        linreg = LinearRegression()
        
        try:
            linreg.fit(x,y)
            linreg_coef = linreg.coef_[0][0]

            ls_linreg_coefs.append(linreg_coef)
            
        except:
            pass

    ls_columns = ['slope_close_' + str(x) for x in range(0,len(ls_linreg_coefs)) ]

    df_linregcoefs = pd.DataFrame(np.array([ls_linreg_coefs]),columns=ls_columns)
    df_linregcoefs
    ###############################################################################################

    # Joins the ss closes df with the slopes df
    df_close_info = pd.concat([df_ssdata1, df_linregcoefs],axis=1,sort=False)
    df_close_info['Datetime'] = Datetime
    
    if i == 0:
        df_close_info_01 = df_close_info.copy()
    else:
        df_close_info_01 = df_close_info_01.append(df_close_info,sort=False).copy()
        
df_close_info_01 = df_close_info_01.reset_index(drop=True)
df_close_info_01

In [ ]:
data = df_analisys_02.iloc[-10:,:]['Close'].tolist()
data.reverse()
plt.scatter(range(0,len(data)), data)
plt.show()

data = df_close_info_01.iloc[0,:][['ss1_close_' + str(x) for x in range(1,10) ]]
plt.scatter(range(0,len(data)), data)
plt.show

In [ ]:
ls_ss1vars = ['ss1_close_' + str(x) for x in range(100,8,-1)]
ls_ss1vars

ls_ss1vars2 = ['ss1_close_' + str(x) for x in range(8,0,-1) ]
ls_ss1vars2

ls_slopevars = ['slope_close_' + str(x) for x in range(0,4) ]
ls_slopevars

In [ ]:
#Assigns correct format to variable to apply transformations
df_close_info_01[ls_ss1vars] = df_close_info_01[ls_ss1vars].astype(float)
df_close_info_01[ls_ss1vars2] = df_close_info_01[ls_ss1vars2].astype(float)
df_close_info_01[ls_slopevars] = df_close_info_01[ls_slopevars].astype(float)

In [ ]:
df_close_info_01 = df_close_info_01[df_close_info_01.notna().all(axis=1)]

df_close_info_01[ls_slopevars + ls_ss1vars2 + ls_ss1vars].info()

In [ ]:
#Defines X vector to all process

X = df_close_info_01[ls_slopevars + ls_ss1vars2 + ls_ss1vars]
print(X.shape)

#y = df_analysis_01[Target_desc]
#y = df_analysis_02[Target_desc + '_coded']
#print(y.shape)

In [ ]:
# Defines the column trasformer
# This will be the standard schema : start with the pipeline for column transformers and then fit the model

#First a lil pip to treat imputation and scalation in one shot for numerical variables


pca_pip = Pipeline(steps=[('pca',PCA(n_components=3)),])


# Defines the column transformer
rf_transformer = ColumnTransformer([("passthrough", "passthrough", ls_slopevars + ls_ss1vars2),
                                     ("pca1", pca_pip, ls_ss1vars),
                                        ]) 

#Prepares pip
pip = Pipeline([('preprocessing', rf_transformer),])


#Fits the pipeline to the data
Xtr = rf_transformer.fit_transform(X)

#Saves the total procedure
#pickle.dump(kmeans_proc, open( DIRECTORY + 'kmeans_proc.pkl', 'wb'))

In [ ]:
Xtr.shape

In [ ]:
#Defines the df of all transformations

ls_ss1pcavars = ['ss1_close_c1','ss1_close_c2','ss1_close_c3']

df_close_info_tr_01 = pd.DataFrame(Xtr,columns=ls_slopevars + ls_ss1vars2 + ls_ss1pcavars)
print(df_close_info_tr_01.shape)
df_close_info_tr_01

In [ ]:
# Concat the Datetime to the transformed data

df_close_info_tr_01 = pd.concat([df_close_info_01['Datetime'],df_close_info_tr_01],axis=1)
df_close_info_tr_01

In [ ]:
pd.concat([df_close_info_01[['Datetime'] +ls_ss1vars2].iloc[0:1,:],
           df_close_info_01[['Datetime'] +ls_ss1vars2].iloc[0:1,:]],axis=0)

## MACD info

### Histogram

In [ ]:
for c in df_analisys_02.columns.tolist():
    print(c)

In [ ]:
# Prepares previos MACD H info as input variables

for i in range(0,len(df_analisys_02)):
    #i=2
    
    ###############################################################################################
    nro_close_lag = 100

    if i==0:
        X = df_analisys_02.iloc[-(nro_close_lag + i):,][['MACDh_12_26_9']]
        Datetime = df_analisys_02.iloc[-1:,]['Datetime'].iloc[0]
    else:
        X = df_analisys_02.iloc[-(nro_close_lag + i):-i,][['MACDh_12_26_9']]
        Datetime = df_analisys_02.iloc[-(i+1):,]['Datetime'].iloc[0]

    # define standard scaler
    sscaler = StandardScaler()

    # transform data
    X_ss1 = sscaler.fit_transform(X)
    #print(X2)

    # Obtains the df of variables of close lags
    ls_columns = ['ss1_macdh_' + str(x) for x in range(len(X_ss1),0,-1) ]
    df_ssdata1 = pd.DataFrame(X_ss1.T,columns=ls_columns)
    ###############################################################################################

    ###############################################################################################
    #Computes slopes before the last close
    ls_linreg_coefs = []
    
    for j in [3,5,8,13]:
        y = X_ss1[-j:]
        x = np.array([range(0,j)]).reshape(-1,1)


        linreg = LinearRegression()
        
        try:
            linreg.fit(x,y)
            linreg_coef = linreg.coef_[0][0]

            ls_linreg_coefs.append(linreg_coef)
            
        except:
            pass

    ls_columns = ['slope_macdh_' + str(x) for x in range(0,len(ls_linreg_coefs)) ]

    df_linregcoefs = pd.DataFrame(np.array([ls_linreg_coefs]),columns=ls_columns)
    df_linregcoefs
    ###############################################################################################

    # Joins the ss closes df with the slopes df
    df_macdh_info = pd.concat([df_ssdata1, df_linregcoefs],axis=1,sort=False)
    df_macdh_info['Datetime'] = Datetime
    
    if i == 0:
        df_macdh_info_01 = df_macdh_info.copy()
    else:
        df_macdh_info_01 = df_macdh_info_01.append(df_macdh_info,sort=False).copy()
        
df_macdh_info_01 = df_macdh_info_01.reset_index(drop=True)
df_macdh_info_01

In [ ]:
data = df_analisys_02.iloc[-9:,:]['MACDh_12_26_9'].tolist()
data.reverse()
plt.scatter(range(0,len(data)), data)
plt.show()

data = df_macdh_info_01.iloc[0,:][['ss1_macdh_' + str(x) for x in range(1,10) ]]
plt.scatter(range(0,len(data)), data)
plt.show()

In [ ]:
# Create variable names lists to naming columns

ls_ss1vars = ['ss1_macdh_' + str(x) for x in range(100,8,-1)]
ls_ss1vars

ls_ss1vars2 = ['ss1_macdh_' + str(x) for x in range(8,0,-1) ]
ls_ss1vars2

ls_slopevars = ['slope_macdh_' + str(x) for x in range(0,4) ]
ls_slopevars

In [ ]:
#Assigns correct format to variable to apply transformations
df_macdh_info_01[ls_ss1vars2] = df_macdh_info_01[ls_ss1vars2].astype(float)
df_macdh_info_01[ls_ss1vars] = df_macdh_info_01[ls_ss1vars].astype(float)
df_macdh_info_01[ls_slopevars] = df_macdh_info_01[ls_slopevars].astype(float)

In [ ]:
df_macdh_info_01 = df_macdh_info_01[df_macdh_info_01.notna().all(axis=1)]

df_macdh_info_01[ls_slopevars + ls_ss1vars2 + ls_ss1vars].info()

In [ ]:
#Defines X vector to all process

X = df_macdh_info_01[ls_slopevars + ls_ss1vars2 + ls_ss1vars]
print(X.shape)

#y = df_analysis_01[Target_desc]
#y = df_analysis_02[Target_desc + '_coded']
#print(y.shape)

In [ ]:
# Defines the column trasformer
# This will be the standard schema : start with the pipeline for column transformers and then fit the model

#First a lil pip to treat imputation and scalation in one shot for numerical variables


pca_pip = Pipeline(steps=[('pca',PCA(n_components=3)),])


# Defines the column transformer
rf_transformer = ColumnTransformer([("passthrough", "passthrough", ls_slopevars + ls_ss1vars2),
                                     ("pca1", pca_pip, ls_ss1vars),
                                        ]) 

#Prepares pip
pip = Pipeline([('preprocessing', rf_transformer),])


#Fits the pipeline to the data
Xtr = rf_transformer.fit_transform(X)

#Saves the total procedure
#pickle.dump(kmeans_proc, open( DIRECTORY + 'kmeans_proc.pkl', 'wb'))

In [ ]:
Xtr.shape

In [ ]:
#Defines the df of all transformations

ls_ss1pcavars = ['ss1_macdh_c1','ss1_macdh_c2','ss1_macdh_c3']

df_macdh_info_tr_01 = pd.DataFrame(Xtr,columns=ls_slopevars + ls_ss1vars2 + ls_ss1pcavars)
print(df_macdh_info_tr_01.shape)
df_macdh_info_tr_01

In [ ]:
# Concat the Datetime to the transformed data

df_macdh_info_tr_01 = pd.concat([df_macdh_info_01['Datetime'],df_macdh_info_tr_01],axis=1)
df_macdh_info_tr_01

In [ ]:
pd.concat([df_macdh_info_tr_01[['Datetime'] +ls_ss1vars2].iloc[0:1,:],
           df_macdh_info_tr_01[['Datetime'] +ls_ss1vars2].iloc[0:1,:]],axis=0)

# VOLUME DATA

In [ ]:
# Prepares previos MACD H info as input variables

for i in range(0,len(df_analisys_02)):
#for i in range(0,1):
    
    ###############################################################################################
    nro_close_lag = 100

    if i==0:
        X = df_analisys_02.iloc[-(nro_close_lag + i):,][['Volume']]
        Datetime = df_analisys_02.iloc[-1:,]['Datetime'].iloc[0]
    else:
        X = df_analisys_02.iloc[-(nro_close_lag + i):-i,][['Volume']]
        Datetime = df_analisys_02.iloc[-(i+1):,]['Datetime'].iloc[0]
        
    if X.loc[max(X.index)][0] == 0:
        X.loc[max(X.index)][0] = X.loc[max(X.index)-1][0]

    # define standard scaler
    sscaler = StandardScaler()

    # transform data
    X_ss1 = sscaler.fit_transform(X)
    #print(X2)

    # Obtains the df of variables of close lags
    ls_columns = ['ss1_vols_' + str(x) for x in range(len(X_ss1),0,-1) ]
    df_ssdata1 = pd.DataFrame(X_ss1.T,columns=ls_columns)
    ###############################################################################################

    
    ###############################################################################################
    #Computes slopes before the last close
    ls_linreg_coefs = []
    
    for j in [3,5,8,13]:
        y = X_ss1[-j:]
        x = np.array([range(0,j)]).reshape(-1,1)


        linreg = LinearRegression()
        
        try:
            linreg.fit(x,y)
            linreg_coef = linreg.coef_[0][0]

            ls_linreg_coefs.append(linreg_coef)
            
        except:
            pass

    ls_columns = ['slope_vols_' + str(x) for x in range(0,len(ls_linreg_coefs)) ]

    df_linregcoefs = pd.DataFrame(np.array([ls_linreg_coefs]),columns=ls_columns)
    df_linregcoefs
    ###############################################################################################

    # Joins the ss closes df with the slopes df
    df_vols_info = pd.concat([df_ssdata1,df_linregcoefs],axis=1,sort=False)
    df_vols_info['Datetime'] = Datetime
    
    if i == 0:
        df_vols_info_01 = df_vols_info.copy()
    else:
        df_vols_info_01 = df_vols_info_01.append(df_vols_info,sort=False).copy()
        
df_vols_info_01 = df_vols_info_01.reset_index(drop=True)
df_vols_info_01

In [ ]:
data = df_analisys_02.iloc[-10:,:]['Volume'].tolist()
data.reverse()
plt.scatter(range(0,len(data)), data)
plt.show()

data = df_vols_info_01.iloc[0,:][['ss1_vols_' + str(x) for x in range(1,10) ]]
plt.scatter(range(0,len(data)), data)
plt.show()

data

In [ ]:
# Create variable names lists to naming columns

ls_ss1vars = ['ss1_vols_' + str(x) for x in range(100,8,-1)]
ls_ss1vars

ls_ss1vars2 = ['ss1_vols_' + str(x) for x in range(8,0,-1) ]
ls_ss1vars2

ls_slopevars = ['slope_vols_' + str(x) for x in range(0,4) ]
ls_slopevars

In [ ]:
#Assigns correct format to variable to apply transformations

df_vols_info_01[ls_ss1vars2] = df_vols_info_01[ls_ss1vars2].astype(float)
df_vols_info_01[ls_ss1vars] = df_vols_info_01[ls_ss1vars].astype(float)
df_vols_info_01[ls_slopevars] = df_vols_info_01[ls_slopevars].astype(float)

In [ ]:
df_vols_info_01 = df_vols_info_01[df_vols_info_01.notna().all(axis=1)]
df_vols_info_01 = df_vols_info_01.reset_index(drop=True)
print(df_vols_info_01.shape)

df_vols_info_01[ls_slopevars + ls_ss1vars2 + ls_ss1vars].info()

In [ ]:
#Defines X vector to all process

X = df_vols_info_01[ls_slopevars + ls_ss1vars2 + ls_ss1vars]
print(X.shape)

In [ ]:
# Defines the column trasformer
# This will be the standard schema : start with the pipeline for column transformers and then fit the model

#First a lil pip to treat imputation and scalation in one shot for numerical variables


pca_pip = Pipeline(steps=[('pca',PCA(n_components=3)),])


# Defines the column transformer
rf_transformer = ColumnTransformer([("passthrough", "passthrough", ls_slopevars + ls_ss1vars2),
                                     ("pca1", pca_pip, ls_ss1vars),
                                        ]) 

#Prepares pip
pip = Pipeline([('preprocessing', rf_transformer),])


#Fits the pipeline to the data
Xtr = rf_transformer.fit_transform(X)

#Saves the total procedure
#pickle.dump(kmeans_proc, open( DIRECTORY + 'kmeans_proc.pkl', 'wb'))

In [ ]:
Xtr.shape

In [ ]:
#Defines the df of all transformations

ls_ss1pcavars = ['ss1_vols_c1','ss1_vols_c2','ss1_vols_c3']

df_vols_info_tr_01 = pd.DataFrame(Xtr,columns=ls_slopevars + ls_ss1vars2 + ls_ss1pcavars)
print(df_vols_info_tr_01.shape)
df_vols_info_tr_01

In [ ]:
# Concat the Datetime to the transformed data

df_vols_info_tr_01 = pd.concat([df_vols_info_01['Datetime'],df_vols_info_tr_01],axis=1)
df_vols_info_tr_01

In [ ]:
pd.concat([df_vols_info_tr_01[['Datetime'] +ls_ss1vars2].iloc[0:1,:],
           df_vols_info_01[['Datetime'] +ls_ss1vars2].iloc[0:1,:]],axis=0)

# Attaches target variable to the df with transformations

In [ ]:
ls_tgcols = ['date','Datetime','Close','target_order','target_order_bin','target_close','target_difference','target_date','target_date_diff']


df_transformations_100 = pd.merge(df_close_info_tr_01,
                           df_macdh_info_tr_01,
                           on = ['Datetime'],
                           how='inner'
                         ).copy()


df_transformations_100 = pd.merge(df_transformations_100,
                           df_vols_info_tr_01,
                           on = ['Datetime'],
                           how='inner'
                         ).copy()

df_analisys_100 = pd.merge(df_transformations_100,
                           df_analisys_02[ls_tgcols],
                           on = ['Datetime'],
                           how='inner'
                         ).copy()


df_analisys_100 = df_analisys_100.sort_values(['Datetime']).reset_index(drop=True)

print(df_analisys_100.shape)

df_analisys_100

In [ ]:
print(min(df_analisys_100['Datetime']))
print(max(df_analisys_100['Datetime']))

In [ ]:
print(df_analisys_100['target_order'].value_counts(dropna=False).reset_index().sort_values(['index'],ascending = True))

In [ ]:
# SAVING POINT

DIR_OUTPUTS = r'C:\Users\willi\Documents\EJERCICIOS\TRADING\outputs/'

df_analisys_100.to_pickle(DIR_OUTPUTS + 'df_spx500_15m_s1' + '.pkl')
print(df_analisys_100.shape)
print(dt.datetime.now())